# Name of your application. Used to uniquely configure containers.
service: dss-lab-owasp-frt

# Name of the container image.
image: markalbrand/dss-lab-owasp-frt

# Deploy to these servers.
servers:
  web:
    - server1.albrand.tech

proxy:
  ssl: true
  host: dss-lab-owasp.albrand.tech
  app_port: 80
  healthcheck:
    interval: 3
    path: /
    timeout: 3

registry:
  username: markalbrand
  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  context: .

aliases:
  shell: app exec --interactive --reuse "bash"

ssh:
  user: deployer # Server user to connect as (default: root)
  keys: ["~/.ssh/hetzner-access"] # List of SSH keys to use for authentication

env:
  VITE_API_URL: 'dss-lab-owasp-bck.albrand.tech'
